---
###################################
# AdoptOpenJDK - Ansible Playbook #
###################################
# Groups can be passed in as a command-line variable in Ansible playbook.
# It can be defined as 'all' or a specific group which the host belongs to.
# For example, it can be 'all' or 'x86' for when a host is in the group 'x86'.
- hosts: "{{ Groups | default('localhost:build:test:!*zos*:!*win*:!*aix*') }}"
  gather_facts: yes
  tasks:
    - block:
      # Set standard variables
        - name: Load AdoptOpenJDKs variable file
          include_vars: group_vars/all/adoptopenjdk_variables.yml
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

  #########
  # Roles #
  #########
  roles:
    - Debug
    - Version
    - Common
